server:
  port: 3251

spring:
  application:
    name: word-box-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_BEHAVIOUR}

springdoc:
  swagger-ui:
    path: /docs/api
